import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

/*
function ActionItem({props}){
    return <li> {props.label} <a href="#">{props.action}</a></li> 
}*/

/* distructuring */
function ActionItem({label, action}){
  return <li> {label} <a href="#">{action}</a></li> 
}

const allCountries = [
  "Russia",
  "USA",
  "China",
  "Spain",
  "Italy",
]

const selectedCountries = [
  "Spain",
  "Italy",
]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Tour Master
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Selected</h2>
            <ul>
              {
                selectedCountries.map( country => <ActionItem label={country} action="-"/> )
              }
            </ul>
          </div>

          <div className={styles.card}>
            <h2>Choose From</h2>
            <ul>
              {
                allCountries.map( country => <ActionItem label={country} action="+"/> )
              }
            </ul>
          </div>

        </div>
      </main>

    </div>
  )
}
